In [ ]:
#Numpy is a library for representing and working with large and multi-dimensional arrays. Array (or matrix) is similar to a 
# list in Python (a 1D array or vector)

In [ ]:
# 2 * [1,2,3] in P would be [1,2,3,1,2,3] - in np it would be [2,4,6] - no 'for' loop needed

In [2]:
import numpy as np

In [ ]:
# Numpy provides an array type that goes above and beyond what Python's built-in lists can do.
# We can create a numpy array by passing a list to the np.array function

In [2]:
a = np.array([1,2,6])

In [ ]:
#We can create a multi-dimensional array by passing a list of lists to the array function

In [5]:
matrix = np.array([[1,2,3], [6,7,8], [5,1,0]])
print(type(matrix)) #nd = n dimensional
print(matrix.shape) # number of rows and columns
print(matrix)

<class 'numpy.ndarray'>
(3, 3)
[[1 2 3]
 [6 7 8]
 [5 1 0]]


In [6]:
x = np.array ([1,2,3])
y = np.array([4,5,6])
x + y

array([5, 7, 9])

In [7]:
x = np.array ([1,2,3])
y = np.array([4,5,6])
x * y

array([ 4, 10, 18])

In [9]:
x + 7 #adding a scalar

array([ 8,  9, 10])

In [ ]:
#Referencing elements in numpy arrays at it's most basic is the same as referencing elements in Python lists.

In [8]:
a[2]

6

In [9]:
matrix[1][2]

8

In [14]:
print(f'Print a: {a}')
print(f"Print a[2] :  {a[2]}")
print(f'Print matrix[1][1]: {matrix[1][1]}')

Print a: [1 2 6]
Print a[2] :  6
Print matrix[1][1]: 7


In [ ]:
# multidimensional numpy arrays are easier to index into. To obtain the element at the 
# second column in the second row, we would write:

In [11]:
print(matrix[1,1])
print(matrix)

7
[[1 2 3]
 [6 7 8]
 [5 1 0]]


In [16]:
matrix[2,2]

0

In [13]:
divisible_by_two = matrix[matrix % 2 == 0]
divisible_by_two

array([2, 6, 8, 0])

In [ ]:
#To get the first 2 elements of the last 2 rows:

In [17]:
matrix[1:, :2] #I don't understand this.

array([[6, 7],
       [5, 1]])

In [ ]:
#Arrays can also be indexed with a boolean sequence used to indicate which values 
#should be included in the resulting array. Boolean sequence must the the same length as the array being indexed.

In [21]:
should_include_elements = [True, False, True] #elemented the middle row of the array
matrix[should_include_elements]

array([[1, 2, 3],
       [5, 1, 0]])

In [19]:
a[should_include_elements] #eliminated the middle element in the list

array([1, 6])

In [ ]:
#Can't add 1 to an array without using a loop using standard python

In [22]:
original_array = [1, 2, 3, 4, 5]
try: #ask about try
    original_array + 1
except TypeError as e: #ask about this.
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [27]:
original_array = [1,2,3,4,5]
original_plus_one = []
for a in original_array:
    original_plus_one.append(a + 1)
print(original_plus_one)

[1, 8, 27, 64, 125]


In [28]:
original_array = [1,2,3,4,5]
original_plus_one = [n + 1 for n in original_array]
print(original_plus_one)

[2, 3, 4, 5, 6]


In [ ]:
# Vectorizing operations means that operations are automatically applied to every element in a vector, which in our 
# case will be a numpy array. So if we are working with a numpy array, we can simply add 1:

In [29]:
original_array = np.array([1, 2, 3, 4, 5])
original_array + 1

array([2, 3, 4, 5, 6])

In [ ]:
#other operators also work

In [32]:
my_array = np.array([-5, 0, 8, 16, 33, 109])

print('my_array      == {}'.format(my_array))
print('my_array - 5  == {}'.format(my_array - 5))
print('my_array * 4  == {}'.format(my_array * 4))
print('my_array / 2  == {}'.format(my_array / 2))
print('my_array ** 2 == {}'.format(my_array ** 2))
print('my_array % 2  == {}'.format(my_array % 2))
print()
print(f'my_array      == {my_array}') # also works for f-string literals
print(f'my_array - 5  == {my_array - 5}')
print(f'my_array * 4  == {my_array * 4}')
print(f'my_array / 2  == {my_array / 2}')
print(f'my_array ** 2 == {my_array ** 2}')
print(f'my_array % 2  == {my_array % 2}')

my_array      == [ -5   0   8  16  33 109]
my_array - 5  == [-10  -5   3  11  28 104]
my_array * 4  == [-20   0  32  64 132 436]
my_array / 2  == [-2.5  0.   4.   8.  16.5 54.5]
my_array ** 2 == [   25     0    64   256  1089 11881]
my_array % 2  == [1 0 0 0 1 1]

my_array      == [ -5   0   8  16  33 109]
my_array - 5  == [-10  -5   3  11  28 104]
my_array * 4  == [-20   0  32  64 132 436]
my_array / 2  == [-2.5  0.   4.   8.  16.5 54.5]
my_array ** 2 == [   25     0    64   256  1089 11881]
my_array % 2  == [1 0 0 0 1 1]


In [ ]:
#Not only are the arithmatic operators vectorized, but the same applies to the comparison operators.

In [34]:
my_array = np.array([-5, 0, 8, 16, 33, 109])
print(f'my_array      == {my_array}')
print(f'my_array - 5  == {my_array == 5}')
print(f'my_array * 4  == {my_array > 7}')
print(f'my_array / 2  == {my_array >= 0}')
print(f'my_array ** 2 == {my_array < 10}')


my_array      == [ -5   0   8  16  33 109]
my_array - 5  == [False False False False False False]
my_array * 4  == [False False  True  True  True  True]
my_array / 2  == [False  True  True  True  True  True]
my_array ** 2 == [ True  True  True False False False]


In [ ]:
#get all positive numbers

In [36]:
my_array[my_array > 0]

array([  8,  16,  33, 109])

In [ ]:
#get all even numbers

In [37]:
my_array[my_array % 2 == 0]

array([ 0,  8, 16])

In [ ]:
#array creation

In [39]:
np.random.randn(15) #numbers drawn from a random normal distribution

array([-0.00776887,  0.48011279, -0.55418826, -1.8643185 ,  1.53690777,
        2.01460061,  1.13677274,  1.78177361, -0.65945111,  1.54661848,
       -0.80088647, -0.03526281, -1.99557896, -1.82130948, -1.18864046])

In [42]:
np.random.randn(4,6)

array([[-1.71475454,  1.99545134, -0.75627701, -1.10371466, -1.3217503 ,
        -0.46371489],
       [-1.69588014,  1.0555763 ,  0.31431091, -0.21245503,  0.89455113,
        -1.06227989],
       [ 1.39586341, -0.04925478,  0.69224917,  0.2376248 , -0.82554716,
         0.12434812],
       [ 0.5680853 , -1.43215708, -1.22476054, -1.52867668, -0.49682946,
         0.98794546]])

In [ ]:
# If we wish to draw from a normal distribution with mean μ and standard deviation σ, we'll need to apply some 
# arithmetic. Recall that to convert from the standard normal distribution, we'll need to multiply by the standard 
# deviation, and add the mean.

In [45]:
mu = 100 #population parameter mean
sigma = 30 #and standard deviation

sigma * np.random.randn(20)  + mu

array([ 90.74934575,  22.0978735 ,  88.10988321, 117.88724935,
        93.24787293, 180.74837412, 132.03151088, 124.89125346,
       120.97951726,  82.61225908, 115.37960801, 117.2751055 ,
       140.2450553 , 105.29294638,  57.55306821,  97.29577158,
        98.47692928, 118.65374532, 167.58312902, 125.80935788])

In [ ]:
# The zeros and ones functions provide the ability to create arrays of a specified size full or either 0s or 1s, 
# and the full function allows us to create an array of the specified size with a default value.

In [48]:
print('np.zeros(3)    == {}'.format(np.zeros(3)))
print('np.ones(3)     == {}'.format(np.ones(3)))
print('np.full(3, 17) == {}'.format(np.full(3, 17)))



np.zeros(3)    == [0. 0. 0.]
np.ones(3)     == [1. 1. 1.]
np.full(3, 17) == [17 17 17]


In [ ]:
#We can also use these methods to create multi-dimensional arrays by passing a tuple of the dimensions of the 
#desired array, instead of a single integer value.

In [52]:
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# Numpy's arange function is very similar to python's builtin range function. It can take a single argument 
# and generate a range from zero up to, but not including, the passed number.

In [53]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# We can also specify a starting point for the range - and step

In [55]:
np.arange(2,21,3)

array([ 2,  5,  8, 11, 14, 17, 20])

In [ ]:
# Unlike python's builtin range, numpy's arange can handle decimal numbers

In [57]:
np.arange(1.3, 81.2, 2.37)

array([ 1.3 ,  3.67,  6.04,  8.41, 10.78, 13.15, 15.52, 17.89, 20.26,
       22.63, 25.  , 27.37, 29.74, 32.11, 34.48, 36.85, 39.22, 41.59,
       43.96, 46.33, 48.7 , 51.07, 53.44, 55.81, 58.18, 60.55, 62.92,
       65.29, 67.66, 70.03, 72.4 , 74.77, 77.14, 79.51])

In [ ]:
# The linspace method creates a range of numbers between a minimum and a maximum, with a set number of elements.
# Note that here the maximum is inclusive.

In [59]:
print('min: 1, max: 4, length = 4 -- {}'.format(np.linspace(1, 4, 4)))
print('min: 1, max: 4, length = 7 -- {} '.format(np.linspace(1, 4, 7))) #I don't understand this answer
print()


min: 1, max: 4, length = 4 -- [1. 2. 3. 4.]
min: 1, max: 4, length = 7 -- [1.  1.5 2.  2.5 3.  3.5 4. ] 



In [60]:
print(f'min: 1, max: 4, length = 4 -- {np.linspace(1, 4, 4)}' #why is this erring?
print(f'min: 1, max: 4, length = 7 -- {np.linspace(1, 4, 7)}'

SyntaxError: invalid syntax (<ipython-input-60-611b65b75fc1>, line 2)

In [ ]:
# math and stats functions

In [66]:
a = np.array([1, 2, 3, 4, 5, 7, 44, 71])

In [70]:
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.std())


1
71
137
17.125
24.32816012360984


In [20]:
numbers = np.array([1,2,3,4,5,6,7,1,8,9,1,4,5,6,8])

In [21]:
numbers == 1

array([ True, False, False, False, False, False, False,  True, False,
       False,  True, False, False, False, False])

In [23]:
mask_above_five = numbers >= 6 #boolean mask

In [24]:
numbers[mask_above_five]

array([6, 7, 8, 9, 6, 8])

In [27]:
fruits = np.array(['banana', 'kiwi', 'mango', 'strawberry', 'tomato'])
type(fruits)
for fruit in fruits:
    print(fruits)


['banana' 'kiwi' 'mango' 'strawberry' 'tomato']
['banana' 'kiwi' 'mango' 'strawberry' 'tomato']
['banana' 'kiwi' 'mango' 'strawberry' 'tomato']
['banana' 'kiwi' 'mango' 'strawberry' 'tomato']
['banana' 'kiwi' 'mango' 'strawberry' 'tomato']


In [28]:
np.full(10, 3.3)

array([3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3])