In [ ]:
#Numpy is a library for representing and working with large and multi-dimensional arrays. 

In [1]:
import numpy as np

In [ ]:
# Numpy provides an array type that goes above and beyond what Python's built-in lists can do.
# We can create a numpy array by passing a list to the np.array function

In [2]:
a = np.array([1,2,6])

In [ ]:
#We can create a multi-dimensional array by passing a list of lists to the array function

In [6]:
matrix = np.array([[1,2,3], [6,7,8], [5,1,0]])
matrix

array([[1, 2, 3],
       [6, 7, 8],
       [5, 1, 0]])

In [ ]:
#Referencing elements in numpy arrays at it's most basic is the same as referencing elements in Python lists.

In [8]:
a[2]

6

In [9]:
matrix[1][2]

8

In [14]:
print(f'Print a: {a}')
print(f"Print a[2] :  {a[2]}")
print(f'Print matrix[1][1]: {matrix[1][1]}')

Print a: [1 2 6]
Print a[2] :  6
Print matrix[1][1]: 7


In [ ]:
# multidimensional numpy arrays are easier to index into. To obtain the element at the 
# second column in the second row, we would write:

In [15]:
matrix[1,1]

7

In [16]:
matrix[2,2]

0

In [ ]:
#To get the first 2 elements of the last 2 rows:

In [17]:
matrix[1:, :2] #I don't understand this.

array([[6, 7],
       [5, 1]])

In [ ]:
#Arrays can also be indexed with a boolean sequence used to indicate which values 
#should be included in the resulting array. Boolean sequence must the the same length as the array being indexed.

In [21]:
should_include_elements = [True, False, True] #elemented the middle row of the array
matrix[should_include_elements]

array([[1, 2, 3],
       [5, 1, 0]])

In [19]:
a[should_include_elements] #eliminated the middle element in the list

array([1, 6])

In [ ]:
#Can't add 1 to an array without using a loop using standard python

In [22]:
original_array = [1, 2, 3, 4, 5]
try: #ask about try
    original_array + 1
except TypeError as e: #ask about this.
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [27]:
original_array = [1,2,3,4,5]
original_plus_one = []
for a in original_array:
    original_plus_one.append(a + 1)
print(original_plus_one)

[1, 8, 27, 64, 125]


In [28]:
original_array = [1,2,3,4,5]
original_plus_one = [n + 1 for n in original_array]
print(original_plus_one)

[2, 3, 4, 5, 6]


In [ ]:
# Vectorizing operations means that operations are automatically applied to every element in a vector, which in our 
# case will be a numpy array. So if we are working with a numpy array, we can simply add 1:

In [29]:
original_array = np.array([1, 2, 3, 4, 5])
original_array + 1

array([2, 3, 4, 5, 6])

In [ ]:
#other operators also work

In [32]:
my_array = np.array([-5, 0, 8, 16, 33, 109])

print('my_array      == {}'.format(my_array))
print('my_array - 5  == {}'.format(my_array - 5))
print('my_array * 4  == {}'.format(my_array * 4))
print('my_array / 2  == {}'.format(my_array / 2))
print('my_array ** 2 == {}'.format(my_array ** 2))
print('my_array % 2  == {}'.format(my_array % 2))
print()
print(f'my_array      == {my_array}') # also works for f-string literals
print(f'my_array - 5  == {my_array - 5}')
print(f'my_array * 4  == {my_array * 4}')
print(f'my_array / 2  == {my_array / 2}')
print(f'my_array ** 2 == {my_array ** 2}')
print(f'my_array % 2  == {my_array % 2}')

my_array      == [ -5   0   8  16  33 109]
my_array - 5  == [-10  -5   3  11  28 104]
my_array * 4  == [-20   0  32  64 132 436]
my_array / 2  == [-2.5  0.   4.   8.  16.5 54.5]
my_array ** 2 == [   25     0    64   256  1089 11881]
my_array % 2  == [1 0 0 0 1 1]

my_array      == [ -5   0   8  16  33 109]
my_array - 5  == [-10  -5   3  11  28 104]
my_array * 4  == [-20   0  32  64 132 436]
my_array / 2  == [-2.5  0.   4.   8.  16.5 54.5]
my_array ** 2 == [   25     0    64   256  1089 11881]
my_array % 2  == [1 0 0 0 1 1]


In [ ]:
#Not only are the arithmatic operators vectorized, but the same applies to the comparison operators.

In [34]:
my_array = np.array([-5, 0, 8, 16, 33, 109])
print(f'my_array      == {my_array}')
print(f'my_array - 5  == {my_array == 5}')
print(f'my_array * 4  == {my_array > 7}')
print(f'my_array / 2  == {my_array >= 0}')
print(f'my_array ** 2 == {my_array < 10}')


my_array      == [ -5   0   8  16  33 109]
my_array - 5  == [False False False False False False]
my_array * 4  == [False False  True  True  True  True]
my_array / 2  == [False  True  True  True  True  True]
my_array ** 2 == [ True  True  True False False False]


In [ ]:
#get all positive numbers

In [36]:
my_array[my_array > 0]

array([  8,  16,  33, 109])

In [ ]:
#get all even numbers

In [37]:
my_array[my_array % 2 == 0]

array([ 0,  8, 16])

In [ ]:
#array creation

In [39]:
np.random.randn(15) #numbers drawn from a random normal distribution

array([-0.00776887,  0.48011279, -0.55418826, -1.8643185 ,  1.53690777,
        2.01460061,  1.13677274,  1.78177361, -0.65945111,  1.54661848,
       -0.80088647, -0.03526281, -1.99557896, -1.82130948, -1.18864046])

In [42]:
np.random.randn(4,6)

array([[-1.71475454,  1.99545134, -0.75627701, -1.10371466, -1.3217503 ,
        -0.46371489],
       [-1.69588014,  1.0555763 ,  0.31431091, -0.21245503,  0.89455113,
        -1.06227989],
       [ 1.39586341, -0.04925478,  0.69224917,  0.2376248 , -0.82554716,
         0.12434812],
       [ 0.5680853 , -1.43215708, -1.22476054, -1.52867668, -0.49682946,
         0.98794546]])