In [ ]:
#Numpy is a library for representing and working with large and multi-dimensional arrays. 

In [1]:
import numpy as np

In [ ]:
# Numpy provides an array type that goes above and beyond what Python's built-in lists can do.
# We can create a numpy array by passing a list to the np.array function

In [2]:
a = np.array([1,2,6])

In [ ]:
#We can create a multi-dimensional array by passing a list of lists to the array function

In [6]:
matrix = np.array([[1,2,3], [6,7,8], [5,1,0]])
matrix

array([[1, 2, 3],
       [6, 7, 8],
       [5, 1, 0]])

In [ ]:
#Referencing elements in numpy arrays at it's most basic is the same as referencing elements in Python lists.

In [8]:
a[2]

6

In [9]:
matrix[1][2]

8

In [14]:
print(f'Print a: {a}')
print(f"Print a[2] :  {a[2]}")
print(f'Print matrix[1][1]: {matrix[1][1]}')

Print a: [1 2 6]
Print a[2] :  6
Print matrix[1][1]: 7


In [ ]:
# multidimensional numpy arrays are easier to index into. To obtain the element at the 
# second column in the second row, we would write:

In [15]:
matrix[1,1]

7

In [16]:
matrix[2,2]

0

In [ ]:
#To get the first 2 elements of the last 2 rows:

In [17]:
matrix[1:, :2] #I don't understand this.

array([[6, 7],
       [5, 1]])

In [ ]:
#Arrays can also be indexed with a boolean sequence used to indicate which values 
#should be included in the resulting array. Boolean sequence must the the same length as the array being indexed.

In [21]:
should_include_elements = [True, False, True] #elemented the middle row of the array
matrix[should_include_elements]

array([[1, 2, 3],
       [5, 1, 0]])

In [19]:
a[should_include_elements] #elemented the middle element in the list

array([1, 6])

In [22]:
original_array = [1, 2, 3, 4, 5]
try: #ask about try
    original_array + 1
except TypeError as e: #ask about this.
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list
